web/router.ex
defmodule GrowJournal.Router do
  use GrowJournal.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  pipeline :admin do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug GrowJournal.Auth, repo: GrowJournal.Repo
  end

  scope "/", GrowJournal do
    pipe_through :browser # Use the default browser stack

    get "/", PageController, :index
    get "/media/*filepath", MediaFilesController, :download

    get "/login", SessionController, :new
    post "/login", SessionController, :create
    get "/logout", SessionController, :delete

    resources "/user_plants", UserPlantController
    resources "/users", UserController, except: [:delete, :edit, :update]
  end

  scope "/admin", GrowJournal.Admin, as: :admin do
    pipe_through :admin

    resources "/users", UserController
    resources "/plants", PlantController do
      resources "/diseases", DiseaseController, except: [:index, :show]
      resources "/pests", PestController, except: [:index, :show]
      resources "/variety", VarietyController, except: [:index, :show]
    end
  end

  scope "/plants", GrowJournal, as: :plants do
    pipe_through :browser

    get "/", PlantController, :index
    get "/:id/", PlantController, :show
  end

  scope "/u", GrowJournal.User, as: :user do
    pipe_through :admin

    get "/", UserHomeController, :index

    get "/change_password", UserHomeController, :change_password
    post "/change_password", UserHomeController, :update_change_password
    put "/change_password", UserHomeController, :update_change_password

    resources "/plants", UserPlantController do
      resources "/events", EventController, except: [:index]
      resources "/pictures", PictureController, except: [:index]
    end
  end


  # Other scopes may use custom stacks.
  # scope "/api", GrowJournal do
  #   pipe_through :api
  # end
end

web/views/layout_view.ex
defmodule GrowJournal.LayoutView do
  use GrowJournal.Web, :view
end

web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Hello GrowJournal!</title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
  </head>

  <body>
  <nav class="navbar navbar-default">
    <div class="container-fluid">
      <div class="navbar-header">
        <a class="navbar-brand" href="<%= user_user_home_path(@conn, :index) %>">
          <img with="30" height="30" alt="GrowJournal Logo" src="<%= static_path(@conn, "/images/logo.svg") %>"/>
        </a>
        <ul class="nav navbar-nav">
          <li><%= link "Grow Journal", to: user_user_home_path(@conn, :index) %></li>
        </ul>
      </div>

      <ul class="nav navbar-nav navbar-right">
        <%= if Plug.Conn.get_session(@conn, :user_id) do %>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link "Admin area", to: admin_user_path(@conn, :index) %></li>
            <li><%= link "My dashboard", to: user_user_home_path(@conn, :index) %></li>
            <li role="separator" class="divider"></li>
            <li><%= link "Change my password", to: user_user_home_path(@conn, :change_password) %></li>
            <li role="separator" class="divider"></li>
            <li><%= link "Logout", to: session_path(@conn, :delete) %></li>
          </ul>
        </li>
        <%= else %>
        <li><%= link "Register", to: user_path(@conn, :new) %></li>
        <li><%= link "Login", to: session_path(@conn, :new) %></li>
        <%= end %>
      </ul>
    </div>
  </nav>
  <div class="container-fluid">
    <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
    <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>

    <main role="main">
      <%= render @view_module, @view_template, assigns %>
    </main>

  </div> <!-- /container-fluid -->
  <script src="//code.jquery.com/jquery-1.12.1.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"
    integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS"
    crossorigin="anonymous">
  </script>
  <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>